### ISSUE TITLE
[chart] not possible to scrape integrations if control plane is disabled

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#417]
**Bug description**

I believe that since we create:
```yaml
  - apiGroups: [ "" ]
    resources:
      - "pods"
      - "nodes"
    verbs: [ "get", "list", "watch" ]
```
if .Values.controlPlane.enabled the nri-discovery is not able to get such info if control plane is disabled.

We are connecting to the kubelet therefore it is a bit different, but still I believe that the request would be denied

**Which chart?**
newrelic infrastructure v3

**Reproduction**

Pending
