### ISSUE TITLE
Renovatebot is not correctly configured for this repository

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-kubernetes#491]
## Is your feature request related to a problem? 
By default, for renovatebot to detect images to be upgraded in the `values.yaml` they must have this structure ([link to the docs](https://docs.renovatebot.com/modules/manager/helm-values/):
```yaml
image:
  repository: 'some-docker/dependency'
  tag: v1.0.0
  registry: registry.example.com # optional key, will default to "docker.io"

coreImage:
  registry: docker.io
  repository: bitnami/harbor-core
  tag: 2.1.3-debian-10-r38
```

But we have this one:
```yaml
images:
  pullSecrets: []
  forwarder:
    pullPolicy: IfNotPresent
    tag: 1.24.1
    repository: newrelic/k8s-events-forwarder
    registry: ""
  agent:
    pullPolicy: IfNotPresent
    tag: 2.8.15
    repository: newrelic/infrastructure-bundle
    registry: ""
```

This has made updates from the infra bundle were lost and this chart has not been properly updated.

## Feature Description
We have to configure RegEx managers so renovatebot is aware of the images that he has to update. We have a working example in the [infrastructure-bundle](https://github.com/newrelic/infrastructure-bundle/blob/9a8d079/.github/renovate.json5#L24-L36)

## Priority
Really Want
