### ISSUE TITLE
Passthrough environment are difficult to be configured

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/nri-kubernetes#500]
### What broke
[Context]( https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent/#passthrough) of the broken feature:

Starting with infrastructure agent 1.14.0, environment variables can be defined in the integrations config file with the {{}} notation. For example:
```
integration_name: com.newrelic.redis
instances:
  - name: redis-metrics
    command: metrics
    arguments:
      hostname: localhost
      port: 6379
      password: {{MY_REDIS_PASSWORD}}
```

Having in the yaml `"{{ MY_REDIS_PASSWORD }}"` or `{{ MY_REDIS_PASSWORD }}` or
```
      password: |-
        {{MY_REDIS_PASSWORD}}
```

results in error at templating time.
Having in the yaml `\{\{ MY_REDIS_PASSWORD \}\}` is rendered but then the agent does not perform the substitution

In V2 `password: "{{MY_REDIS_PASSWORD}}"` used to work

### Workaround 
 The passthrough env variables uses unfortunately the very same chars `{{}}` than Helm and therefore the template cannot be rendered correctly.

I tested locally a workaround that seems to be working:
Having in the values:

```
[...]
      integrations:
        - name: nri-rabbitmq
          env:
            HOSTNAME: '{{ printf "{{ NR_RMQ_HOSTNAME }}" }}'
            USERNAME: '{{ printf "{{ NR_RMQ_USERNAME }}" }}'
            PASSWORD: '{{ printf "{{ NR_RMQ_PASSWORD }}" }}' 
[...]
```

and just for testing setting:
```
[...]
  kubelet:
    extraEnv:
      - name: NR_RMQ_HOSTNAME
        value: secret-hostname
      - name: NR_RMQ_USERNAME
        value: secret-username
      - name: NR_RMQ_PASSWORD
        value: secret-password 
[...]
```

The section in the integration config is rendered as:

```
[...]
    - env:                
        HOSTNAME: '{{ NR_RMQ_HOSTNAME }}'
        PASSWORD: '{{ NR_RMQ_PASSWORD }}'
        USERNAME: '{{ NR_RMQ_USERNAME }}'
[...]
```

In the agent logs I can see that the env vars have been correctly populated

```
time="2022-06-24T08:33:20Z" level=debug msg="Running command." command=/var/db/newrelic-infra/newrelic-integrations/bin/nri-rabbitmq component=integrations.Executor env="[NRI_CONFIG_INTERVAL=30s HOSTNAME=secret-hostname <HIDDEN> CLUSTER_NAME=fg NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME=test-hostname PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PORT=15672 USERNAME=secret-username <HIDDEN> NRI_HOST_ID=minikube]" path=/var/db/newrelic-infra/newrelic-integrations/bin/nri-rabbitmq
time="2022-06-24T08:33:21Z" level=info msg="Integration stderr (not parsed)." component=integrations.runner.Runner env=newrelic integration_name=nri-rabbitmq line="[ERR] Error collecting Node data: [Get \"http://secret-hostname:15672/api/nodes\": dial tcp: lookup secret-hostname on 10.96.0.10:53: no such host]" role=rabbitmq  
```

### Next Step

 - We should try to fix the old behaviour allowing `password: "{{MY_REDIS_PASSWORD}}"`.

 - If not possible we need to improve and document current workaround

 - We need to improve documentation anyway since this is an important feature a bit undocumented
