### ISSUE TITLE
KSM data was not populated after trying all endpoints

### ISSUE THREAD

**Issue by RoyVandenBroeck** [newrelic/nri-kubernetes#530]
When installing the nri-kubernetes/newrelic-infrastructure helm chart on our Openshift v4.10 the nrk8s-ksm deployment is not able to collect metrics from the kube-state-metrics. This causes it to crash and keep restarting.

The kube-state-metrics pod only accepts traffic via https. The certificate it uses is only valid in it's own namespace (openshift-monitoring). Since the chart is deployed in it's own namespace this is not useable.

## Our environment:
OpenShift version: 4.10.14
                                                         
NAME: nri-kubernetes/newrelic-infrastructure
CHART VERSION: 3.8.0 
APP VERSION: 3.4.1  

## logs/examples
curl from the new relic namespace to kube-state-metrics-pod
```
curl https://x.x.x.x:8443/metrics
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html
```

KSM scraper-configmap with scheme: http
```
level=warning msg="Error populating KSM metrics: populate errors:, querying KSM: getting filtered metric families: error calling prometheus exposed metrics endpoint. Got status code: 400"
level=warning msg="Error populating KSM metrics: populate errors:, querying KSM: getting filtered metric families: error calling prometheus exposed metrics endpoint. Got status code: 400"
level=error msg="retrieving scraper data: retrieving ksm data: KSM data was not populated after trying all endpoints"
```
KSM scraper-configmap with scheme: https
```
level=warning msg="Error populating KSM metrics: populate errors:, querying KSM: getting filtered metric families: fetching metrics from \"https://198.18.6.9:8443/metrics\": Get \"https://x.x.x.x:8443/metrics\": x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs"
level=warning msg="Error populating KSM metrics: populate errors:, querying KSM: getting filtered metric families: fetching metrics from \"https://198.18.6.9:9443/metrics\": Get \"https://x.x.x.x:9443/metrics\": x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs"
level=error msg="retrieving scraper data: retrieving ksm data: KSM data was not populated after trying all endpoints"
```

scraper-configmap.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: newrelic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: newrelic-infrastructure
    app.kubernetes.io/version: 3.4.1
    helm.sh/chart: newrelic-infrastructure-3.8.0
  name: newrelic-nrk8s-ksm
  namespace: newrelic
data:
  nri-kubernetes.yml: |-
    interval: 30s
    namespaceSelector: {}
    ksm:
      enabled: true
      retries: 3
      scheme: https
      selector: app.kubernetes.io/name=kube-state-metrics
      timeout: 10s
```

Helm values.yaml
```
customSecretName: "newrelic-licensekey-secret"
customSecretLicenseKey: "licensekey"

serviceAccount:
  create: true
  name: newrelic

lowDataMode: true

controlPlane:
  config:
    etcd:
      enabled: true
      autodiscover:
        - selector: "k8s-app=etcd"
          namespace: kube-system
          matchNode: true
          endpoints:
            - url: https://localhost:9979
              insecureSkipVerify: true
              auth:
                type: mTLS
                mtls:
                  secretName: kube-etcd-client-certs
                  secretNamespace: newrelic

enableProcessMetrics: false
```
