### ISSUE TITLE
ETCD metrics for clusters in Rancher

### ISSUE THREAD

**Issue by evegaval** [newrelic/nri-kubernetes#549]
## Is your feature request related to a problem? Please describe.
Extra steps required to scrape etcd metrics for k8s clusters  in Rancher (static endpoints).

## Feature Description
We have been able to scrape the control plane components metrics, including etcd by having something like this.
```
    config:
      etcd:
        enabled: true
        staticEndpoint:
          url: https://localhost:2379
          insecureSkipVerify: true
          auth:
            type: mTLS
            mtls:
              secretName: nri-bundle-etcd-cert
              secretNamespace: newrelic
      scheduler:
        enabled: true
        staticEndpoint:
          url: http://localhost:10251
          insecureSkipVerify: true
          auth:
            type: bearer
      controllerManager:
        enabled: true
        staticEndpoint:
          url: http://localhost:10252
          insecureSkipVerify: true
          auth:
            type: bearer
      apiServer:
        enabled: true
        staticEndpoint:
          url: https://localhost:6443
          insecureSkipVerify: true
          auth:
            type: bearer
```
What I am looking for is to simplify the process to create the secret with the cert and key for etcd to work. Currently we manually create the secret, but we have several clusters which would require too many manual steps to get this done.

I would like to know if there is any alternative, like mounting a host path (`/etc/kubernetes/ssl/`) to avoid manual steps and make the installation process as simple as possible.

## Describe Alternatives
Manually create and deploy the secret for every k8s cluster you have.

## Priority
Really Want

Thank you very much!!!
