### ISSUE TITLE
ksm pod `creating integration wrapper: applying option: timeout waiting for agent: probe timed out after 1m30s`

### ISSUE THREAD

**Issue by diclophis** [newrelic/nri-kubernetes#604]
## Description

After applying the `nri-bundle` `v5.0.2` helm chart, the `app.kubernetes.io/component=ksm` and `app.kubernetes.io/component=kublet` pods have to "restart" at least 1 time due to a timeout mentioned in the logs

```
# ...
time="2023-01-19T02:18:24Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:29Z" level=debug msg="probe attempt to http://localhost:8002/v1/data/ready failed: Get \"http://localhost:8002/v1/data/ready\": dial tcp [::1]:8002: connect: connection refused"
time="2023-01-19T02:18:29Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:34Z" level=debug msg="probe attempt to http://localhost:8002/v1/data/ready failed: Get \"http://localhost:8002/v1/data/ready\": dial tcp [::1]:8002: connect: connection refused"
time="2023-01-19T02:18:34Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:39Z" level=debug msg="probe attempt to http://localhost:8002/v1/data/ready failed: Get \"http://localhost:8002/v1/data/ready\": dial tcp [::1]:8002: connect: connection refused"
time="2023-01-19T02:18:39Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:44Z" level=debug msg="probe attempt to http://localhost:8002/v1/data/ready failed: Get \"http://localhost:8002/v1/data/ready\": dial tcp [::1]:8002: connect: connection refused"
time="2023-01-19T02:18:44Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:49Z" level=debug msg="probe attempt to http://localhost:8002/v1/data/ready failed: Get \"http://localhost:8002/v1/data/ready\": dial tcp [::1]:8002: connect: connection refused"
time="2023-01-19T02:18:49Z" level=debug msg="Retrying in 5s"
time="2023-01-19T02:18:54Z" level=error msg="creating integration wrapper: applying option: timeout waiting for agent: probe timed out after 1m30s"
```

I believe this is due to a bug in the implementation of the timeout logic of the https://github.com/newrelic/nri-kubernetes/blob/main/src/integration/wrapper.go#L23 that does not allow this `1m30s` window to modified.

I think the root of the issue is because of the `newrelic-infrastructure` agent has a bug in the `cloud discovery` module that prevents it from detecting the `GetInstanceId` in a timely manner here: https://github.com/newrelic/infrastructure-agent/blob/0392302333b9fbf1cff0a2811fa575b3e18c8914/pkg/sysinfo/cloud/cloud.go#L136-L142

The gist of the broken cycle is ... the newrelic agent container `-c forwarder` attempts to initialize the `NewAWSHarvester` client synchronously, gets into the `detect()` block, calls through to `GetInstanceId` ... which subsequently calls to `GetHarvester` which raises a `ErrDetectorNotInitialized` ... because it is not initialized yet ... BUT ... the kicker is, it is trying now to initialize so it gets stuck, and ends up falling back to the "async retry loop" and ultimately skips detecting the `CloudType` due to a timeout... This also means we are missing some of the meta information from the nrk8s ksm monitoring data.

## Expected Behavior

The `nri-bundle` chart should install cleanly and not cause a consistent restarted pod upon initial install. It should also be possibly to change any internal timeout via ENV toggles, but I cannot find a way to make the `1m30s` timeout adjustable.

## Steps to Reproduce

Install the `nri-bundle` helm chart w/ the following helm `.Values`

```
        serviceAccount:
          name: xxx
        global:
          cluster: xxx
          customSecretLicenseKey: xxx
          customSecretName: xxx
          tolerations:
            - key: "node.kubernetes.io/disk-pressure"
              effect: "NoSchedule"
            - key: "node.kubernetes.io/memory-pressure"
              effect: "NoSchedule"
            - key: "node.kubernetes.io/network-unavailable"
              effect: "NoSchedule"
            - key: "node.kubernetes.io/not-ready"
              effect: "NoSchedule"
            - key: "node.kubernetes.io/unreachable"
              effect: "NoSchedule"
            - key: "node.kubernetes.io/unschedulable"
              effect: "NoSchedule"
          config:
            verboseLog: true
          verboseLog: true
        nri-kube-events:
          enabled: true
        nri-prometheus:
          enabled: true
        newrelic-logging:
          enabled: true
        newrelic-infrastructure:
          verboseLog: true
          controlPlane:
            enabled: false
```

## Your Environment

The pods are running in a namespace on a `AWS EKS` cluster, `kube version 1.24`

## Additional context

Once the pods get past the timeouts (and after one restart at least) the agent seems to be reporting ok. I also think the issue belongs here (possibly also in the `newrelic-infrastructure` repo (I think thats where to root-root of the bug is) ... the `nri-bundle` helm chart seems to be functioning correctly as far as starting the modules in this repo... but maybe there is a bug in the yaml helm template that prevents the timeout override from working.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
