### ISSUE TITLE
KSM exporter crashes when custom `stateset` type metric is exposed instead of being ignored

### ISSUE THREAD

**Issue by lauraseidler** [newrelic/nri-kubernetes#711]
## Description
We are deploying the `newrelic-bundle` via the Helm chart. We already have a separate instance of kube-state-metrics deployed which we would like to use - this generally works fine. As part of our kube-state-metrics installation, we have configured a custom metric of type `stateset`, which is [officially supported](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md#stateset). This makes the exporter crash with the following error:
```
ksm time="2023-04-06T16:22:21Z" level=info msg="Waiting for agent container to be ready..."                                                 
ksm time="2023-04-06T16:22:21Z" level=info msg="New Relic Kubernetes integration Version: v3.9.0, Platform: linux/amd64, GoVersion: go1.19.7,
GitCommit: 59350fc4f55faa485023c2a071b2cbcc9847ba42, BuildDate: Tue Mar 21 19:52:20 UTC 2023\n"                                            
ksm time="2023-04-06T16:22:21Z" level=warning msg="Error populating KSM metrics: populate errors:, querying KSM: getting filtered metric fami
lies: parsing metrics: reading text format failed: text format parsing error in line 6899: unknown metric type \"stateset\""                
ksm time="2023-04-06T16:22:21Z" level=error msg="retrieving scraper data: retrieving ksm data: KSM data was not populated after trying all en
dpoints"
```

## Expected Behavior
Given that this a custom metric which we're not expecting to show up in New Relic, I would expect that this just gets ignored.

## Steps to Reproduce
We use the following custom metric definition:
```yaml
---
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: elasticsearch.k8s.elastic.co
        kind: Elasticsearch
        version: v1
      # Use custom prefix to shorten the resulting name without risking metric conflicts
      metricNamePrefix: kube_custom
      metrics:
        - name: "elasticsearch_health_status"
          help: "Elasticsearch CRD health status"
          each:
            type: StateSet
            stateSet:
              labelName: status
              path: [status, health]
              # States (except "unknown") can be found here: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html
              list: [green, yellow, red, unknown]
          labelsFromPath:
            namespace: [metadata, namespace]
            name: [metadata, name]
```

This generates output like this:
```
# HELP kube_custom_elasticsearch_health_status Elasticsearch CRD health status
# TYPE kube_custom_elasticsearch_health_status stateset
kube_custom_elasticsearch_health_status{customresource_group="elasticsearch.k8s.elastic.co",customresource_kind="Elasticsearch",customresource_version="v1",name="test",namespace="test",status="green"} 1
kube_custom_elasticsearch_health_status{customresource_group="elasticsearch.k8s.elastic.co",customresource_kind="Elasticsearch",customresource_version="v1",name="test",namespace="test",status="red"} 0
kube_custom_elasticsearch_health_status{customresource_group="elasticsearch.k8s.elastic.co",customresource_kind="Elasticsearch",customresource_version="v1",name="test",namespace="test",status="unknown"} 0
kube_custom_elasticsearch_health_status{customresource_group="elasticsearch.k8s.elastic.co",customresource_kind="Elasticsearch",customresource_version="v1",name="test",namespace="test",status="yellow"} 0
```

## Your Environment
Chart version: `newrelic-infrastructure-3.14.0`
kube-state-metrics version: `2.8.2`

## Additional context

https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md#stateset
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#stateset

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
