### ISSUE TITLE
enableProcessMetrics doesn't support string version of "true"/"false"

### ISSUE THREAD

**Issue by edwardcookemacu** [newrelic/nri-kubernetes#835]
^^ Provide a general summary of the issue in the title above. ^^ 

## Description
Setting `enableProcessMetrics` to `"true"` doesn't take effect. We need to be able to do this since we use ArgoCD to deploy the K8s charts and it sets it as a string, instead of only just `true`/`false`.

## Expected Behavior
It accepts `"true"` or `"false"` as well as `true` or `false`

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
Nothing here, it doesn't apply the value.

## Steps to Reproduce
Use the following ArgoCD application manifest
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newrelic
  labels:
    app.kubernetes.io/part-of: newrelic
spec:
  project: default
  source:
    repoURL: 'https://helm-charts.newrelic.com'
    chart: nri-bundle
    targetRevision: 5.0.4
    helm:
      parameters:
      - name: "global.customSecretName"
        value: newrelic
      - name: "global.customSecretLicenseKey"
        value: NEW_RELIC_LICENSE_KEY
      - name: "global.cluster"
        value: XXX
      - name: "newrelic-infrastructure.privileged"
        value: "true"
      - name: "global.lowDataMode"
        value: "true"
      - name: "ksm.enabled"
        value: "true"
      - name: "kubeEvents.enabled"
        value: "true"
      - name: "newrelic-prometheus-agent.enabled"
        value: "true"
      - name: "logging.enabled"
        value: "true"
      - name: "newrelic-pixie.enabled"
        value: "true"
      - name: "newrelic-pixie.customSecretApiKeyName"
        value: newrelic-pixie
      - name: "newrelic-pixie.customSecretApiKeyKey"
        value: NEW_RELIC_PIXIE_API_KEY
      - name: "pixie-chart.enabled"
        value: "true"
      # The deploy key may be read from a custom secret in the Pixie namespace. This secret should be formatted where the key of the deploy key is "deploy-key".
      - name: "pixie-chart.customDeployKeySecret"
        value: newrelic-pixie
      - name: "pixie-chart.clusterName"
        value: XXX
      - name: "enableProcessMetrics"
        value: true
  destination:
    namespace: newrelic
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
```

## Your Environment
We use chart 5.0.3 right now with ArgoCD latest version to deploy it.

## Additional context
This line requires it to be a `bool` type, if it was also to check if it was set to `"true"` it should take care of it I think.

https://github.com/newrelic/nri-kubernetes/blob/ef41132b728bce07d1b02c01856b444ef716ea42/charts/newrelic-infrastructure/templates/kubelet/_agent-config_helper.tpl#L16C5-L16C5

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
