### ISSUE TITLE
Log spam of "cpuLimitCores metric not available. using default max 96 cores" in nri-kubernetes 3.15.3

### ISSUE THREAD

**Issue by LHCGreg** [newrelic/nri-kubernetes#854]
## Description
After updating  nri-kubernetes in the newrelic-kubelet Daemonset to 3.15.3 (used in the latest nri-bundle helm chart), daemonset pods log dozens of messages like `time="2023-08-16T19:56:15Z" level=warning msg="cpuLimitCores metric not available. using default max 96 cores"` every `<interval>` seconds. The problem is not present in nri-kubernetes 3.15.2. It seems to be linked to commit 923a16c149ae48e11e20a3ed46bcb582526dcddd.

## Expected Behavior
I expected the logs to be fairly clean. Having pods with cpu request but not cpu limit is commonly recommended. Logging this message only once, or once per day, or something like that would be sufficient instead of logging it for every pod every X seconds.

## Steps to Reproduce
Run nri-kubernetes 3.15.3 in the newrelic-kubelet Daemonset on a node that has pods with a cpu request but not a cpu limit?

## Your Environment

EKS 1.24.

newrelic-kubelet daemonset configuration:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: newrelic
    app.kubernetes.io/name: newrelic-infrastructure
    app.kubernetes.io/version: 3.15.3
    helm.sh/chart: newrelic-infrastructure-3.20.3
    mode: privileged
  name: newrelic-kubelet
  namespace: newrelic
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: kubelet
      app.kubernetes.io/instance: newrelic
      app.kubernetes.io/name: newrelic-infrastructure
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: kubelet
        app.kubernetes.io/instance: newrelic
        app.kubernetes.io/name: newrelic-infrastructure
        mode: privileged
    spec:
      containers:
      - env:
        - name: NRI_KUBERNETES_CLUSTERNAME
          value: <REDACTED>
        - name: NRI_KUBERNETES_SINK_HTTP_PORT
          value: "8003"
        - name: NRI_KUBERNETES_VERBOSE
          value: "false"
        - name: NRI_KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRI_KUBERNETES_NODEIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: newrelic/nri-kubernetes:3.15.3
        imagePullPolicy: IfNotPresent
        name: kubelet
        resources:
          limits:
            memory: 300M
          requests:
            cpu: 100m
            memory: 150M
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 2000
          runAsUser: 1000
        volumeMounts:
        - mountPath: /etc/newrelic-infra/nri-kubernetes.yml
          name: nri-kubernetes-config
          subPath: nri-kubernetes.yml
      - args:
        - newrelic-infra
        env:
        - name: CLUSTER_NAME
          value: <REDACTED>
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: newrelic-license
        - name: NRIA_OVERRIDE_HOSTNAME_SHORT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRIA_OVERRIDE_HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRI_KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: CLUSTER_NAME
        - name: NRIA_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: newrelic/infrastructure-bundle:3.2.12
        imagePullPolicy: IfNotPresent
        name: agent
        ports:
        - containerPort: 8003
        resources:
          limits:
            memory: 300M
          requests:
            cpu: 100m
            memory: 150M
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/newrelic-infra.yml
          name: config
          subPath: newrelic-infra.yml
        - mountPath: /etc/newrelic-infra/integrations.d/
          name: nri-integrations-cfg-volume
        - mountPath: /dev
          name: dev
        - mountPath: /run/containerd/containerd.sock
          name: host-containerd-socket
        - mountPath: /var/log
          name: log
        - mountPath: /host
          name: host-volume
          readOnly: true
        - mountPath: /var/db/newrelic-infra/data
          name: agent-tmpfs-data
        - mountPath: /var/db/newrelic-infra/user_data
          name: agent-tmpfs-user-data
        - mountPath: /tmp
          name: agent-tmpfs-tmp
      hostNetwork: false
      imagePullSecrets:
      - name: docker-hub-credential
      priorityClassName: system-node-critical
      serviceAccountName: newrelic
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /dev
        name: dev
      - hostPath:
          path: /run/containerd/containerd.sock
        name: host-containerd-socket
      - hostPath:
          path: /var/log
        name: log
      - hostPath:
          path: /
        name: host-volume
      - emptyDir: {}
        name: agent-tmpfs-data
      - emptyDir: {}
        name: agent-tmpfs-user-data
      - emptyDir: {}
        name: agent-tmpfs-tmp
      - configMap:
          items:
          - key: nri-kubernetes.yml
            path: nri-kubernetes.yml
          name: newrelic-kubelet-ddmd59hbc6
        name: nri-kubernetes-config
      - configMap:
          items:
          - key: newrelic-infra.yml
            path: newrelic-infra.yml
          name: newrelic-agent-kubelet-59t5httm7k
        name: config
      - configMap:
          name: newrelic-integrations-cfg-6ct58987ht
        name: nri-integrations-cfg-volume
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

## Additional context
I also found forum post https://forum.newrelic.com/s/hubtopic/aAX8W000000PGknWAG/warning-cpulimitcores-metric-not-available that has a couple other people that ran into this.
