### ISSUE TITLE
There is no way to add passthrough environment variable to agent with nri-flex intigration

### ISSUE THREAD

**Issue by utkarsh079** [newrelic/nri-kubernetes#875]
## Description
I am trying to create an integration with nri-flex to create an api call to kubernetes api to get config information regarding operator

``` integrations:
      nri-flex-stackgressample.yaml:
      integrations:
        - name: nri-flex
          config:
            name: StackGresCluster
            global:
              tls_config:
                insecure_skip_verify: True
            apis:
              - event_type: StackGresClusterSample
                url: "https://kubernetes.default.svc/apis/stackgres.io/v1/sgclusters/"
                headers:
                  Authorization: Bearer $$KUBE_TOKEN
```
I am adding 'KUBE_TOKEN' as an environment variable and adding it as passthrough_environment in values.yaml for helm chart.

```
kubelet:
    extraEnv:
      - name: KUBE_TOKEN
        valueFrom:
          secretKeyRef:
            name: <secret-name>
            key: token
    agentConfig:
      passthrough_environment: ["KUBE_TOKEN"]
```

## Expected Behavior
"KUBE_TOKEN" should be added as passthrough environment variable but its not.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
`time="2023-09-12T14:01:03Z" level=debug msg="Running command." command=/var/db/newrelic-infra/newrelic-integrations/bin/nri-flex component=integrations.Executor env="[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin NRI_CONFIG_INTERVAL=30s CONFIG_PATH=/tmp/discovered1592592200 CLUSTER_NAME=testNEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME=test VERBOSE=1 NRI_HOST_ID=i-xxx]" integration_name=nri-flex path=/var/db/newrelic-infra/newrelic-integrations/bin/nri-flex`

In templates, I can see that `NRIA_PASSTHROUGH_ENVIRONMENT` is hardcoded and its not using agentConfig at all
[Link](https://github.com/newrelic/nri-kubernetes/blob/71f487e38b859db723711a4df869283772992cb2/charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml#L162)
